runtime: go
env: flex

automatic_scaling:
  min_num_instances: 1

#api_version: go1

#handlers:
#- url: /.*
#  script: _go_app
#
#env_variables:
#  POSTGRES_CONNECTION: "cloudsql='reda-188106:us-central1:uptown' user=postgres password='C0AcD8dBOri7ust9' dbname=geometric"

env_variables:
  POSTGRES_CONNECTION: "user=postgres password=C0AcD8dBOri7ust9 dbname=geometric host=/cloudsql/reda-188106:us-central1:uptown"

beta_settings:
  cloud_sql_instances: reda-188106:us-central1:uptown