runtime: go
env: flex

automatic_scaling:
  min_num_instances: 1

#[START env]
env_variables:
  # See https://godoc.org/github.com/lib/pq
  #
  # Replace INSTANCE_CONNECTION_NAME with the same value as in the
  # beta_settings section below.
  # POSTGRES_CONNECTION: "user=postgres password=C0AcD8dBOri7ust9 dbname=geometric host=/cloudsql/reda-188106:us-central1:uptown"
  #
  # If you're testing locally using the Cloud SQL proxy with TCP,
#     instead set this environment variable:
  POSTGRES_CONNECTION="user=postgres password=C0AcD8dBOri7ust9 dbname=geometric sslmode=disable"
#[END env]

#[START cloudsql_settings]
# Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
# Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
# For SQL v2 instances, this should be in the form of "project:region:instance".
# Cloud SQL v1 instances are not supported.
beta_settings:
  cloud_sql_instances: reda-188106:us-central1:uptown
#[END cloudsql_settings]